version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-server
  
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"
    container_name: react-frontend